import Link from 'next/link';
import { Card, CardContent } from '@/components/ui/card';
import { buttonClass } from '@/components/ui/button';
import type { SolutionRecommendation } from '@/lib/revenue/types';
import { RevenueEventTracker } from '@/components/revenue/revenue-event-tracker';

export function ContextualOffer({ recommendation, token }: { recommendation: SolutionRecommendation; token: string }) {
  return <section id="solution" className="scroll-mt-24" aria-labelledby="solution-title"><RevenueEventTracker token={token} event="solution_recommendation_viewed" /><p className="eyebrow text-blue-200">Kontextová DCZ ponuka</p><h2 id="solution-title" className="section-title">Odporúčaný smer: {recommendation.title}</h2><p className="mt-4 max-w-3xl leading-7 text-slate-400">{recommendation.summary}</p><div className="mt-7 grid gap-4 lg:grid-cols-[1fr_1fr]"><Card className="border-blue-300/15"><CardContent><h3 className="text-xl font-semibold text-white">Prečo tento rozsah</h3><ul className="mt-4 space-y-3 text-sm leading-6 text-slate-300">{recommendation.rationale.length ? recommendation.rationale.map((reason) => <li key={reason} className="flex gap-3"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-blue-300" />{reason}</li>) : <li>Odporúčanie je zatiaľ orientačné. Doplňte ROI a kvalifikáciu.</li>}</ul></CardContent></Card><Card><CardContent><h3 className="text-xl font-semibold text-white">Odporúčané moduly</h3><div className="mt-4 flex flex-wrap gap-2">{recommendation.recommendedModules.map((module) => <span key={module} className="sample-badge">{module}</span>)}</div>{recommendation.excludedModules.length > 0 && <p className="mt-5 text-xs leading-5 text-slate-500">Zatiaľ nezahŕňame: {recommendation.excludedModules.join(', ')}.</p>}</CardContent></Card></div><div className="mt-6 flex flex-col gap-3 sm:flex-row"><Link href={`/book/${encodeURIComponent(token)}`} className={buttonClass('primary')}>{recommendation.nextStepLabel}</Link><Link href={`/audit/${encodeURIComponent(token)}/manual-review`} className={buttonClass('secondary')}>Požiadať o manuálne overenie</Link></div></section>;
}
