import Link from 'next/link';
import type { LeadRecord } from '@/lib/db/schema';

const priorityStyle: Record<string, string> = { A: 'border-rose-300/20 bg-rose-400/10 text-rose-100', B: 'border-amber-300/20 bg-amber-400/10 text-amber-100', C: 'border-blue-300/20 bg-blue-400/10 text-blue-100', nurture: 'border-white/10 bg-white/[.03] text-slate-300', disqualified: 'border-slate-500/20 bg-slate-500/10 text-slate-400' };

export function LeadTable({ leads }: { leads: LeadRecord[] }) {
  const ordered = [...leads].sort((a, b) => ({ A: 4, B: 3, C: 2, nurture: 1, disqualified: 0 }[b.priority] ?? 0) - ({ A: 4, B: 3, C: 2, nurture: 1, disqualified: 0 }[a.priority] ?? 0) || b.createdAt.getTime() - a.createdAt.getTime());
  return <div className="overflow-x-auto rounded-2xl border border-white/8"><table className="min-w-full divide-y divide-white/8 text-left text-sm"><thead className="bg-white/[0.03] text-xs tracking-wide text-slate-500 uppercase"><tr><th className="px-4 py-3">Kontakt</th><th className="px-4 py-3">Priorita</th><th className="px-4 py-3">Fit / Intent</th><th className="px-4 py-3">Stav</th><th className="px-4 py-3">Firma / model</th><th className="px-4 py-3">Vytvorený</th></tr></thead><tbody className="divide-y divide-white/6">{ordered.map((lead) => <tr key={lead.id} className="hover:bg-white/[0.025]"><td className="px-4 py-4"><Link className="font-medium text-white hover:text-blue-300" href={`/admin/leads/${lead.id}`}>{lead.name || lead.email}</Link><span className="mt-1 block text-xs text-slate-600">{lead.email} · {lead.emailVerifiedAt ? 'overený' : 'neoverený'}</span></td><td className="px-4 py-4"><span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-semibold ${priorityStyle[lead.priority] ?? priorityStyle.nurture}`}>{lead.priority}</span></td><td className="px-4 py-4 text-slate-300">{lead.fitScore}/50 · {lead.intentScore}/50</td><td className="px-4 py-4 text-slate-300">{lead.stage}</td><td className="px-4 py-4 text-slate-300">{lead.company || '—'}<span className="mt-1 block text-xs text-slate-600">{lead.vertical || 'unknown'} · {lead.businessModel || 'unknown'}</span></td><td className="px-4 py-4 text-slate-500">{lead.createdAt.toLocaleString('sk-SK')}</td></tr>)}{ordered.length === 0 && <tr><td colSpan={6} className="px-4 py-8 text-center text-slate-500">Zatiaľ nie sú uložené žiadne leady.</td></tr>}</tbody></table></div>;
}
