import Link from 'next/link';
import { notFound } from 'next/navigation';
import { LeadWorkflowForm } from '@/components/admin/lead-workflow-form';
import { BookingStatusForm } from '@/components/admin/booking-status-form';
import { Card, CardContent } from '@/components/ui/card';
import { findAuditById, findLeadById } from '@/lib/db/queries';
import { leadRevenueContext } from '@/lib/db/revenue-queries';
import { buildRevenueContext } from '@/lib/revenue/context';
import { decisionRoleLabel, investmentLabel, timelineLabel } from '@/lib/revenue/labels';

function euro(value: number): string { return new Intl.NumberFormat('sk-SK', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 }).format(value); }

export default async function AdminLeadDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const lead = await findLeadById(id); if (!lead) notFound(); const audit = lead.auditId ? await findAuditById(lead.auditId) : null; const stored = await leadRevenueContext(lead); const revenue = audit?.reportJson ? await buildRevenueContext(audit, lead) : null; const q = stored.qualification?.qualificationJson; const roi = stored.roi?.scenarioJson;
  return <div><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex gap-2"><span className="sample-badge observed">Priority {lead.priority}</span><span className="sample-badge">{lead.routingStatus}</span></div><h1 className="mt-3 text-3xl font-semibold text-white">{lead.name || lead.email}</h1><p className="mt-2 text-slate-500">{lead.email} · {lead.emailVerifiedAt ? 'e-mail overený' : 'e-mail neoverený'}</p></div>{audit && <Link className="text-sm text-blue-300 hover:text-blue-200" href={`/admin/audits/${audit.id}`}>Otvoriť audit →</Link>}</div>
  <div className="mt-8 grid gap-4 lg:grid-cols-[1fr_1fr_0.9fr]"><Card><CardContent><dl className="space-y-4 text-sm"><div><dt className="text-slate-500">Firma</dt><dd className="mt-1 text-white">{lead.company || 'neuvedená'}</dd></div><div><dt className="text-slate-500">Telefón</dt><dd className="mt-1 text-white">{lead.phone || 'neuvedený'}</dd></div><div><dt className="text-slate-500">Fit / Intent</dt><dd className="mt-1 text-white">{lead.fitScore}/50 · {lead.intentScore}/50 · celkom {lead.leadScore}/100</dd></div><div><dt className="text-slate-500">Vertikála / model</dt><dd className="mt-1 text-white">{lead.vertical || 'unknown'} · {lead.businessModel || 'unknown'}</dd></div><div><dt className="text-slate-500">Atribúcia</dt><dd className="mt-1 text-white">{[lead.utmSource, lead.utmMedium, lead.utmCampaign].filter(Boolean).join(' / ') || 'neuvedená'}</dd></div></dl></CardContent></Card>
  <Card><CardContent><h2 className="font-semibold text-white">Obchodný kontext</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-slate-400">{lead.primaryGoal || 'Bez doplňujúcej správy.'}</p>{q && <dl className="mt-5 space-y-3 text-sm"><div><dt className="text-slate-500">Rola / termín</dt><dd className="text-white">{decisionRoleLabel[q.decisionRole]} · {timelineLabel[q.projectTimeline]}</dd></div><div><dt className="text-slate-500">Investičný rozsah</dt><dd className="text-white">{investmentLabel[q.investmentBand]}</dd></div></dl>}<p className="mt-5 break-all text-xs text-slate-500">Audit: {audit?.targetUrl ?? lead.auditTargetSnapshot}</p></CardContent></Card>
  <Card><CardContent><h2 className="mb-5 font-semibold text-white">Obchodný workflow</h2><LeadWorkflowForm lead={lead} /></CardContent></Card></div>
  <div className="mt-5 grid gap-4 lg:grid-cols-3">{roi && <Card><CardContent><p className="eyebrow text-emerald-200">ROI</p><p className="mt-3 text-sm text-slate-400">Realistický ročný model</p><p className="mt-2 text-2xl font-semibold text-white">{roi.realisticAnnualPotential ? `${euro(roi.realisticAnnualPotential.min)} – ${euro(roi.realisticAnnualPotential.max)}` : 'Nedostatok vstupov'}</p></CardContent></Card>}{revenue && <Card><CardContent><p className="eyebrow">Odporúčanie</p><h2 className="mt-3 text-xl font-semibold text-white">{revenue.recommendation.title}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{revenue.recommendation.summary}</p></CardContent></Card>}{stored.booking && <Card><CardContent><p className="eyebrow text-violet-200">Booking</p><p className="mt-3 text-xl font-semibold text-white">{stored.booking.status}</p><p className="mt-2 text-sm text-slate-500">Referencia {stored.booking.publicReference}</p><BookingStatusForm leadId={lead.id} currentStatus={stored.booking.status} /></CardContent></Card>}</div>
  {lead.scoreReasonsJson?.length ? <Card className="mt-5"><CardContent><h2 className="font-semibold text-white">Prečo má lead túto prioritu</h2><div className="mt-4 flex flex-wrap gap-2">{lead.scoreReasonsJson.map((reason) => <span key={reason} className="sample-badge">{reason}</span>)}</div></CardContent></Card> : null}</div>;
}
