import type { CaseStudy } from '@/lib/revenue/types';

export const CASE_STUDIES: CaseStudy[] = [
  {
    id: 'fitness-membership-flow',
    slug: 'fitness-clenstvo-a-platby',
    title: 'Fitness členstvo, programy a online platby',
    verticals: ['fitness_wellness'],
    problems: ['conversion', 'transaction', 'trust'],
    solutionIds: ['growth_funnel', 'revenue_platform'],
    proofType: 'delivered_project',
    summary: 'Technické riešenie prepájajúce ponuku členstva, programy a externé platobné odkazy v jasnom konverznom toku.',
    challenge: 'Návštevník potreboval rýchlo pochopiť ponuku, vybrať produkt a prejsť k platbe bez komplikovanej administrácie.',
    implemented: ['Produktové balíky', 'Stripe Payment Links', 'Mobilná konverzná cesta', 'Bezpečné formuláre'],
    disclaimer: 'Ide o popis dodaného riešenia. Finančné výsledky klienta neboli verejne overené a preto ich neuvádzame.',
  },
  {
    id: 'b2b-value-portal',
    slug: 'b2b-saas-value-portal',
    title: 'B2B SaaS Value Intelligence Portal',
    verticals: ['b2b_saas', 'professional_services'],
    problems: ['message_clarity', 'conversion', 'follow_up_measurement'],
    solutionIds: ['growth_funnel', 'revenue_platform'],
    proofType: 'concept',
    summary: 'Modelový návrh B2B funnelu od diagnostiky cez platený výstup až po obchodný follow-up.',
    challenge: 'Komplexný produkt potreboval preložiť hodnotu do zrozumiteľného business case a kvalifikovaného predajného hovoru.',
    implemented: ['Assessment flow', 'Executive preview', 'Lead qualification', 'CRM/admin koncept'],
    disclaimer: 'Ide o transparentne označený koncept, nie tvrdenie o nasadenom klientskom výsledku.',
  },
  {
    id: 'developer-revenue-platform',
    slug: 'developerska-revenue-platforma',
    title: 'Revenue platforma pre rezidenčný projekt',
    verticals: ['developer_real_estate'],
    problems: ['trust', 'conversion', 'transaction'],
    solutionIds: ['revenue_platform'],
    proofType: 'concept',
    summary: 'Modelový systém dostupnosti jednotiek, rezervácií, leadov a obchodného adminu.',
    challenge: 'Developer potrebuje znížiť trenie medzi záujmom o projekt a kvalifikovaným kontaktom na predajcu.',
    implemented: ['Dostupnosť jednotiek', 'Pôdorysy', 'Rezervačný krok', 'Obchodný dashboard'],
    disclaimer: 'Ide o produktový koncept. Neuvádza neoverené predajné výsledky.',
  },
  {
    id: 'professional-client-center',
    slug: 'klientske-centrum-profesionalnych-sluzieb',
    title: 'Klientske centrum pre profesionálne služby',
    verticals: ['professional_services'],
    problems: ['trust', 'conversion', 'follow_up_measurement'],
    solutionIds: ['conversion_foundation', 'growth_funnel'],
    proofType: 'delivered_project',
    summary: 'Klientske rozhranie a jasnejšia cesta od služby k objednávke alebo kontaktu.',
    challenge: 'Služba potrebovala zjednodušiť komunikáciu hodnoty a presunúť časť procesu do digitálneho kanála.',
    implemented: ['Service UX', 'Kontaktný funnel', 'Klientske centrum', 'Bezpečné spracovanie formulárov'],
    disclaimer: 'Ide o popis dodaného technického riešenia bez neoverených tvrdení o výnosoch.',
  },
];
